spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moyu_brush?useUnicode=true&useSSL=false
      &characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2001chendi
